/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeolsun;

import java.util.ArrayList;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import static projeolsun.MainFrame.deftm;

/**
 *
 * @author Beyza
 */
public class ekleFrame extends javax.swing.JFrame {

    /**
     * Creates new form ekleFrame
     */
    public ekleFrame() {
        initComponents();
        this.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        evSa_ad_lbl.setEnabled(false);
        evSa_tel_lbl.setEnabled(false);
        evSah_ad_txt.setEnabled(false);
        evSah_soyad_txt.setEnabled(false);
        evSah_tel_txt.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AdSoyadLAbel = new javax.swing.JLabel();
        TelefonLabel = new javax.swing.JLabel();
        BlokLabel = new javax.swing.JLabel();
        noLabel = new javax.swing.JLabel();
        ad_txt = new javax.swing.JTextField();
        soyad_txt = new javax.swing.JTextField();
        telefon_txt = new javax.swing.JTextField();
        kiraci_chbox = new javax.swing.JCheckBox();
        evSah_ad_txt = new javax.swing.JTextField();
        evSah_soyad_txt = new javax.swing.JTextField();
        evSa_tel_lbl = new javax.swing.JLabel();
        evSah_tel_txt = new javax.swing.JTextField();
        evSa_ad_lbl = new javax.swing.JLabel();
        blok_cmbx = new javax.swing.JComboBox<>();
        no_cmbx = new javax.swing.JComboBox<>();
        ekle_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Daire Ekle");
        setBackground(new java.awt.Color(240, 200, 240));
        setFocusTraversalPolicyProvider(true);
        setForeground(new java.awt.Color(240, 240, 240));
        setName("Daire Ekle"); // NOI18N

        AdSoyadLAbel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        AdSoyadLAbel.setText("Ad Soyad");

        TelefonLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TelefonLabel.setText("Telefon");

        BlokLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BlokLabel.setText("Blok");
        BlokLabel.setFocusTraversalPolicyProvider(true);

        noLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        noLabel.setText("No");
        noLabel.setFocusTraversalPolicyProvider(true);

        ad_txt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        soyad_txt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        telefon_txt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        kiraci_chbox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        kiraci_chbox.setText("Kiracı");
        kiraci_chbox.setFocusTraversalPolicyProvider(true);
        kiraci_chbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kiraci_chboxActionPerformed(evt);
            }
        });

        evSah_ad_txt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        evSah_ad_txt.setFocusTraversalPolicyProvider(true);
        evSah_ad_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                evSah_ad_txtActionPerformed(evt);
            }
        });
        evSah_ad_txt.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                evSah_ad_txtPropertyChange(evt);
            }
        });

        evSah_soyad_txt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        evSah_soyad_txt.setFocusTraversalPolicyProvider(true);

        evSa_tel_lbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        evSa_tel_lbl.setText("Ev Sahibi Telefon");
        evSa_tel_lbl.setFocusTraversalPolicyProvider(true);

        evSah_tel_txt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        evSah_tel_txt.setFocusTraversalPolicyProvider(true);

        evSa_ad_lbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        evSa_ad_lbl.setText("Ev Sahibi Ad Soyad");
        evSa_ad_lbl.setFocusTraversalPolicyProvider(true);
        evSa_ad_lbl.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                evSa_ad_lblPropertyChange(evt);
            }
        });

        blok_cmbx.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        blok_cmbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D" }));
        blok_cmbx.setFocusTraversalPolicyProvider(true);
        blok_cmbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blok_cmbxActionPerformed(evt);
            }
        });

        no_cmbx.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        no_cmbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6" }));

        ekle_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ekle_btn.setText("Ekle");
        ekle_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ekle_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(evSa_tel_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(34, 34, 34)
                                    .addComponent(evSah_tel_txt))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(evSa_ad_lbl)
                                            .addGap(18, 18, 18)
                                            .addComponent(evSah_ad_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(30, 30, 30))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(TelefonLabel)
                                                .addComponent(BlokLabel))
                                            .addGap(117, 117, 117)
                                            .addComponent(blok_cmbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(106, 106, 106)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(noLabel)
                                        .addComponent(evSah_soyad_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(kiraci_chbox))
                        .addGap(0, 44, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(telefon_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(AdSoyadLAbel)
                                .addGap(101, 101, 101)
                                .addComponent(ad_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(soyad_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(no_cmbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ekle_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(156, 156, 156))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AdSoyadLAbel)
                    .addComponent(ad_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(soyad_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TelefonLabel)
                    .addComponent(telefon_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BlokLabel)
                    .addComponent(noLabel)
                    .addComponent(blok_cmbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(no_cmbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(kiraci_chbox)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(evSah_soyad_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(evSa_ad_lbl)
                    .addComponent(evSah_ad_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(evSa_tel_lbl)
                    .addComponent(evSah_tel_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(ekle_btn)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void evSah_ad_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_evSah_ad_txtActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_evSah_ad_txtActionPerformed

    private void evSah_ad_txtPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_evSah_ad_txtPropertyChange
        // TODO add your handling code here:

    }//GEN-LAST:event_evSah_ad_txtPropertyChange

    private void evSa_ad_lblPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_evSa_ad_lblPropertyChange
        // TODO add your handling code here:

    }//GEN-LAST:event_evSa_ad_lblPropertyChange

    private void kiraci_chboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kiraci_chboxActionPerformed
        // TODO add your handling code here:
        evSa_ad_lbl.setEnabled(kiraci_chbox.isSelected());
        evSa_tel_lbl.setEnabled(kiraci_chbox.isSelected());
        evSah_ad_txt.setEnabled(kiraci_chbox.isSelected());
        evSah_soyad_txt.setEnabled(kiraci_chbox.isSelected());
        evSah_tel_txt.setEnabled(kiraci_chbox.isSelected());

    }//GEN-LAST:event_kiraci_chboxActionPerformed

    private void ekle_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ekle_btnActionPerformed
        // TODO add your handling code here:
        AidatFrame.dtm.setRowCount(0);
        MainFrame.deftm.setRowCount(0);
        Pattern pattern = Pattern.compile("[0-9]{10}");
        Matcher m = pattern.matcher(telefon_txt.getText());

        for (Daire d : Daire.daireler) {
            if (blok_cmbx.getSelectedItem().equals(d.blok) && no_cmbx.getSelectedItem().equals(d.daire)) {
                JOptionPane.showMessageDialog(this, "Bu daire zaten ekli.");
                MainFrame.listele();
               return;
           } }
                if(m.find()){
                if (kiraci_chbox.isSelected()) {
                    Resident r = new Kiracı(evSah_tel_txt.getText(), evSah_ad_txt.getText(), evSah_soyad_txt.getText(), ad_txt.getText(), soyad_txt.getText(), telefon_txt.getText());
                    Daire dai = new Daire(r, blok_cmbx.getSelectedItem().toString(), no_cmbx.getSelectedItem().toString());
                    Daire.daireler.add(dai);
                    
                } else {
                    Resident r = new EvSahibi(ad_txt.getText(), soyad_txt.getText(), telefon_txt.getText());
                    Daire dai = new Daire(r, blok_cmbx.getSelectedItem().toString(), no_cmbx.getSelectedItem().toString());
                    Daire.daireler.add(dai);
                }
                
                }
                else{
                    JOptionPane.showMessageDialog(this, "Telefonu 10 basamaklı giriniz.");
                    return;
                }
                

            

        

//        AidatFrame.dtm.addRow(new String[]{Daire.daireler.get(i).blok,Daire.daireler.get(i).daire,"Mevcut Değil","Mevcut Değil"});
//        MainFrame.deftm.addRow(new String[]{Daire.daireler.get(i).blok,Daire.daireler.get(i).daire,"Mevcut Değil","Mevcut Değil"});
        int k = 1;
        String durum = "Sakin";
        for (Daire d : Daire.daireler) {
            if (d.r instanceof EvSahibi) {
                durum = "Ev Sahibi";
            } else if (d.r instanceof Kiracı) {
                durum = "Kiracı";
            }
            
            deftm.addRow(new String[]{String.valueOf(k), d.r.ad, d.r.soyad, String.valueOf(d.r.telefon), d.blok, d.daire, durum});
            k++;

        }
        this.setVisible(false);
    }//GEN-LAST:event_ekle_btnActionPerformed

    private void blok_cmbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blok_cmbxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_blok_cmbxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ekleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ekleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ekleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ekleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ekleFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdSoyadLAbel;
    private javax.swing.JLabel BlokLabel;
    private javax.swing.JLabel TelefonLabel;
    private javax.swing.JTextField ad_txt;
    private javax.swing.JComboBox<String> blok_cmbx;
    private javax.swing.JButton ekle_btn;
    private javax.swing.JLabel evSa_ad_lbl;
    private javax.swing.JLabel evSa_tel_lbl;
    private javax.swing.JTextField evSah_ad_txt;
    private javax.swing.JTextField evSah_soyad_txt;
    private javax.swing.JTextField evSah_tel_txt;
    private javax.swing.JCheckBox kiraci_chbox;
    private javax.swing.JLabel noLabel;
    private javax.swing.JComboBox<String> no_cmbx;
    private javax.swing.JTextField soyad_txt;
    private javax.swing.JTextField telefon_txt;
    // End of variables declaration//GEN-END:variables
}
